server:
  servlet:
    context-path: "/api"

springdoc:
  openapi:
    version: 0.0.1
    host: ${APPLICATION_HOST}
  oidc:
    url: ${OIDC_PROVIDER_CONFIG_URL}
  swagger-ui:
    oauth:
      client-id: ${OIDC_CLIENT_ID}
      use-pkce-with-authorization-code-grant: true

spring:
  security:
    api-key:
      path: "/key"
    token:
      claims:
        email: "email"
        first-name: "given_name"
        last-name: "family_name"
        authorities: "realm_access.roles"
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OIDC_PROVIDER_JWK_URL}
        opaquetoken:
          client-id: ${OIDC_CLIENT_ID}
