OIDC_PROVIDER_CONFIG_URL: https://todo.com/
OIDC_PROVIDER_JWK_URL: https://todo.com/
OIDC_CLIENT_ID: unused

feature:
  users:
    generate: false
    in-memory: true

springdoc:
  openapi:
    host: https://todo.com/
