server:
  servlet:
    context-path: "/api"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/auth/realms/master/protocol/openid-connect/certs
        opaquetoken:
          client-id: app

springdoc:
  oidc:
    url: http://localhost:8081/auth/realms/master/.well-known/openid-configuration
  swagger-ui:
    oauth:
      client-id: app
      use-pkce-with-authorization-code-grant: true

security:
  api-key:
    path: "/apikey"
  token:
    claims:
      email: "email"
      first-name: "given_name"
      last-name: "family_name"
      authorities: "realm_access.roles"
