server:
  servlet:
    context-path: "/api"

springdoc:
  oidc:
    url: ${OIDC_PROVIDER_CONFIG_URL}
  swagger-ui:
    oauth:
      client-id: ${OIDC_SWAGGER_CLIENT_ID}
      use-pkce-with-authorization-code-grant: true

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: ${DATABASE_DIALECT}
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OIDC_PROVIDER_JWK_URL}
        opaquetoken:
          client-id: ${OIDC_SERVER_CLIENT_ID}
          client-secret: ${OIDC_SERVER_CLIENT_SECRET}

token:
  role-defaults: [ 'READ', 'WRITE', 'DELETE' ]
  role-mappings: {
    admin: [ 'ADMIN' ]
  }
  claims:
    email: "email"
    username: "preferred_username"
    first-name: "given_name"
    last-name: "family_name"
    authorities: "realm_access.roles"
