SERVER_HOST: http://localhost:8080
DATABASE_URL: jdbc:postgresql://localhost:5432/
DATABASE_USERNAME: postgres
DATABASE_PASSWORD: postgres
DATABASE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
OIDC_PROVIDER_CONFIG_URL: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_6wOiibFgH/.well-known/openid-configuration
OIDC_PROVIDER_JWK_URL: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_6wOiibFgH/.well-known/jwks.json
OIDC_USER_INFO_ENDPOINT: https://sanderkrabbenborg.auth.eu-west-1.amazoncognito.com/oauth2/userInfo
OIDC_SERVER_CLIENT_ID: cnp2398b24cvkm
OIDC_SERVER_CLIENT_SECRET: pOEV7HOTZ2zYnHHH9gCPFxGp21Lz7Z8D
OIDC_SWAGGER_CLIENT_ID: nclas9841-aSDA
