DATABASE_URL: jdbc:h2:mem:testdb
DATABASE_DIALECT: org.hibernate.dialect.H2Dialect
DATABASE_USERNAME: username
DATABASE_PASSWORD: password
OIDC_PROVIDER_CONFIG_URL: http://useGeneratedApiKey/
OIDC_PROVIDER_JWK_URL: http://useGeneratedApiKey/
OIDC_SERVER_CLIENT_ID: useGeneratedApiKey
OIDC_SERVER_CLIENT_SECRET: useGeneratedApiKey
OIDC_SWAGGER_CLIENT_ID: useGeneratedApiKey

feature:
  dev:
    generate-user: true
