server:
  host: ${SERVER_HOST}

springdoc:
  oidc:
    url: ${OIDC_PROVIDER_CONFIG_URL}
  swagger-ui:
    oauth2-redirect-url: ${SERVER_HOST}/swagger-ui/oauth2-redirect.html
    oauth:
      client-id: ${OIDC_SWAGGER_CLIENT_ID}
      use-pkce-with-authorization-code-grant: true

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: ${DATABASE_DIALECT}
    show-sql: true
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OIDC_PROVIDER_JWK_URL}
        opaquetoken:
          client-id: ${OIDC_SERVER_CLIENT_ID}
          client-secret: ${OIDC_SERVER_CLIENT_SECRET}

auth:
  role:
    claim: "cognito:groups"
    defaults: [ 'READ', 'WRITE', 'DELETE' ]
    mappings: {
      admin: [ 'ADMIN' ]
    }
  user-info:
    endpoint: ${OIDC_USER_INFO_ENDPOINT}
    email: "email"
    username: "preferred_username"
    first-name: "given_name"
    last-name: "family_name"
