SERVER_HOST: http://localhost:8080
DATABASE_URL: jdbc:h2:mem:testdb
DATABASE_USERNAME: username
DATABASE_PASSWORD: password
DATABASE_DIALECT: org.hibernate.dialect.H2Dialect
OIDC_PROVIDER_CONFIG_URL: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_6wOiibFgH/.well-known/openid-configuration
OIDC_PROVIDER_JWK_URL: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_6wOiibFgH/.well-known/jwks.json
OIDC_USER_INFO_ENDPOINT: https://sanderkrabbenborg.auth.eu-west-1.amazoncognito.com/oauth2/userInfo
OIDC_SERVER_CLIENT_ID: cnp2398b24cvkm
OIDC_SERVER_CLIENT_SECRET: pOEV7HOTZ2zYnHHH9gCPFxGp21Lz7Z8D
OIDC_SWAGGER_CLIENT_ID: nclas9841-aSDA

feature:
  dev:
    generate-user: true
    generated-user-id: 66a2b3b0-2244-42b1-bcaa-ae97ff0b49a9
